language: python
python:
    - "2.6"
    - "2.7"

# Installs the dependencies
install:
    - pip install . --use-mirrors
    - pip install -r requirements.txt --use-mirrors
    - pip install python-memcached

# Only runs on master
branches:
  only:
    - master

script: python tests/test_jeeves.py
